#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run check-types ||
(
    echo 'Failed Type check'
    false;
)

npm run check-format ||
(
    echo 'Prettier check Faile. Run npm run format, add changes and try commit again';
    false;
)


npm run check-lint ||
(
    echo 'Eslint check Faile. Make the required changes listed above, add changes and try commit again';
    false;
)


npm run build ||
(
    echo 'Build failed : View the errors above to see why';
    false;
)