# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: REACT CI

on:
  push:
    branches:
      - main # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      page_url: https://jeepra-dev.github.io/cv
    steps:
    - name: Set PUBLIC_URL
      run: echo "PUBLIC_URL=https://jeepra-dev.github.io/cv" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: build # change to your build folder
